# Turn on LED light strip in kitchen between dusk and dawn at a low, non-white light if the main light isn't on
- id: kitchen_dim_overnight
  alias: Kitchen night lighting
  trigger:
  - platform: state
    entity_id: binary_sensor.kitchen_motion
    from: 'off'
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: "{{ state_attr('sun.sun', 'elevation') < -6 }}"
      - condition: template
        value_template: "{{ state_attr('sensor.hue_motion_sensor_1_light_level','lightlevel') < 16000 }}"
  action:
  - service: light.turn_on
    entity_id: light.rgbw_light_strip_5m
    data:
      brightness: 130
      rgb_color:
        - 255
        - 153
        - 51
      white_value: 0
# Turn off LED strip light after detecting no motion
- id: kitchen_dim_overnight_off
  alias: Kitchen night lighting off
  trigger:
  - platform: state
    entity_id: binary_sensor.kitchen_motion
    to: 'off'
    for: '00:02:00'
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: "{{ state_attr('sun.sun', 'elevation') < -6 }}"
      - condition: template
        value_template: "{{ state_attr('sensor.hue_motion_sensor_1_light_level','lightlevel') < 16000 }}"
  action:
  - service: light.turn_off
    entity_id: light.rgbw_light_strip_5m
  
