version: "3"
services:
    mosquitto:
      container_name: mosquitto
      image: eclipse-mosquitto:latest
      volumes:
        - $HOME/.mosquitto/config:/mosquitto/config
        - $HOME/.mosquitto/data:/mosquitto/data
        - $HOME/.mosquitto/log:/mosquitto/log
        - /etc/localtime:/etc/localtime:ro
      ports:
        - "1883:1883"
        - "9001:9001"
      restart: always
    homeassistant:
      container_name: homeassistant
      image: homeassistant/raspberrypi3-homeassistant:stable
      depends_on:
        - mosquitto
      volumes:
        - $HOME/.homeassistant:/config
        - /etc/localtime:/etc/localtime:ro
      network_mode: host
      privileged: true
      restart: always
    nodered:
      container_name: nodered
      image: nodered/node-red:latest
      depends_on:
        - homeassistant
        - mosquitto
      volumes:
        - $HOME/.node-red:/data
        - /etc/localtime:/etc/localtime:ro
      ports:
        - "1880:1880"
      restart: always